### ISSUE TITLE
Make it possible to add local support groups on map

### ISSUE THREAD

**Issue by overby-me** [burnpiro/uasupport#9]
In Denmark (and maybe in many other countries) local support groups are organized as Facebook groups.
It would be useful, if it was possible, to add them to the uasupport map.

**Comment by burnpiro** [comment]
At this moment you're able to add "Organization" account with all the members being either "Manager" or "Volunteer" but that is not something like facebook group, rather just a way to structure organizations like non-profit associations. Creating a copy of facebook (messaging, sharing, etc) is not that easy. I mean, it is easy to implement but drains a lot of resources (mostly because of realtime DB for messaging and file sharing).

**Comment by overby-me** [comment]
If we can add the uasupport organization to the map, with a link to a Facebook group, then it would be perfect.
I didn't mean that everything should be synced between uasupport and FB.

**Comment by overby-me** [comment]
Maybe we can just add Facebook support groups as an option in Aid Center?
Then you can add an address and a link to the Facebook group.

**Comment by burnpiro** [comment]
I've added a separate section for support groups, there is an option to select the language and there is no location (FB group has no physical location). It should be deployed soon.

**Comment by overby-me** [comment]
@burnpiro In Denmark they actually usually have a location, because they are organized around specific cities/towns.
